spring:
  application:
    name: client
network:
  host: 127.0.0.1
  port: 10000
  group: default
netty:
  client:
    clientWorkerThreads: 4
    clientOnewaySemaphoreValue: 65535
    clientAsyncSemaphoreValue: 65535
    connectTimeoutMillis: 3000
    channelNotActiveInterval: 60000
    clientChannelMaxIdleTimeSeconds: 120
    clientSocketSndBufSize: 65535
    clientSocketRcvBufSize: 65535
    clientPooledByteBufAllocatorEnable: true
    clientCloseSocketIfTimeout: true
    useTLS: false







